### ISSUE TITLE
the pdf from `geta` has very thin lines 

### ISSUE THREAD

**Issue by weiwu-zhang** [juruen/rmapi#167]
Compare to the screenshot:
![sketch](https://user-images.githubusercontent.com/548435/113850353-b4187380-97dd-11eb-83dc-4bd31e41dcc3.png)

The PDF look pretty bad. Lines are way too thin:

[AlchemyNFT-annotations.pdf](https://github.com/juruen/rmapi/files/6270762/AlchemyNFT-annotations.pdf)

At first, I thought the PDF must be generated at the server side and it's remarkable's cloud server to blame

But then the PDF exported from their mobile app looked perfect:

[AlchemyNFT (1).pdf](https://github.com/juruen/rmapi/files/6270774/AlchemyNFT.1.pdf)

**Comment by ddvk** [comment]
well, the pdf rendering is not optimal, but what do you expect, without specs it is not very easy. Also this seems to be done with the caligraphy pen, which was never added

**Comment by martin-braun** [comment]
A well known problem, that has been discussed before. I better working alternative is [remarks](https://github.com/lucasrla/remarks), but it's harder to get to work and you still need to build a script to do download your zip packages using `rmapi`.

My biggest wish is to use `rmapi` for everything, because it's so easy to use, but sometimes I need better exports of annotations.

**Comment by ddvk** [comment]
i made cmd line tool with someone else's go code: [rm-convert](https://github.com/ddvk/rm-convert). just `rmapi get file` then try the zip with it

**Comment by martin-braun** [comment]
@ddvk That's awesome, but it will export either all pages or only pages with marks, but not both, right? If it is possible to get both modes working, why not bringing this to `rmapi`? I appreciate your PRs in this repo a lot.
